export enum ActionType {
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAIL = 'LOGIN_FAIL',
    SIGNUP_REQUEST = 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
    SIGNUP_FAIL = 'SIGNUP_FAIL',
    SEND_NETWORK_FAIL = 'SEND_NETWORK_FAIL',
    CLEAR_NETWORK_FAIL = 'CLEAR_NETWORK_FAIL'
}
